server:
  port: 8080
spring:
  application:
    name: grpcclient

grpc:
  client:
    grpcserver:
      address: 'static://127.0.0.1:9898'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
